### ISSUE TITLE
Custom text

### ISSUE THREAD

**Issue by nonameolsson** [oskarkrawczyk/heyoffline.js#28]
I can't figure out how to change the text. I've tried with the following code
```
new Heyoffline({
  text.title: "Heading",
  text.content: "Warning Text",
  text.button: "Close Warning" 
} ) ;
```

But I just get some error messages. `Uncaught SyntaxError: Unexpected token .`

What could be wrong?

**Comment by tovic** [comment]
Try this:

~~~ .javascript
{
  text: {
    title: "Heading",
    content: "Warning Text",
    button: "Close Warning"
  }
}
~~~

Take a look &rarr; https://github.com/oskarkrawczyk/heyoffline.js/blob/676f702ee42cc32ce15290b43a4e42f7f8cad1d5/heyoffline.js#L58&L62

**Comment by oskarkrawczyk** [comment]
Yes, obviously this is not a valid object key `{text.title: "..."}`
